---
title: "Pilot Anlaysis"
author: "Carmen Emborski"
date: "4/19/2018"
output: html_document
---

```{r setup, include=FALSE}
library(RCurl); packageVersion("RCurl")
library(ggplot2); packageVersion("ggplot2")
library(grid); packageVersion("grid")
library(gridExtra); packageVersion("gridExtra")
library(RColorBrewer); packageVersion("RColorBrewer")
library(reshape); packageVersion("reshape")
library(car); packageVersion("car")
library(lmtest); packageVersion("lmtest")
library(tidyr); packageVersion("tidyr")
library(dplyr); packageVersion("dplyr")
library(plyr); packageVersion("plyr")
library(broom); packageVersion("broom")
library(boot); packageVersion("boot")
library(nlme); packageVersion("boot")
library(multcomp); packageVersion("multcomp")
```
Import data. Data file can be found in master repository.
```{r}
data <- read.csv(text=getURL("https://raw.githubusercontent.com/cemborski/DynamicTransgenerationalPlasticity_SupplementaryMaterials/master/Supplementary%20Figures%20and%20Tables/Pilot/Pilot%20Data.csv"))
  
```

Treatment Effects
```{r}
#Female Glycogen
data$Treatment <- factor(data$Treatment, levels=c("CD", "NSD", "LSD", "HSD"))
data$Sex <- factor(data$Sex, levels=c("female", "male"))

#Run Models
Y.0F.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F0"))
Y.1F.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F1"))
Y.2F.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F2"))
Y.3F.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F3"))
Y.4F.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F4"))
Y.5F.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F5"))

#Create Dataframe of Results (See Y.results.df)
lastThree <- function(x) substr(x, nchar(x)-2, nchar(x))
Y.F.results.df <- rbind(tidy(Y.0F.Mod) %>% mutate(model = "F0"),
                 tidy(Y.1F.Mod) %>% mutate(model = "F1"),
                 tidy(Y.2F.Mod) %>% mutate(model = "F2"),
                 tidy(Y.3F.Mod) %>% mutate(model = "F3"),
                 tidy(Y.4F.Mod) %>% mutate(model = "F4"),
                 tidy(Y.5F.Mod) %>% mutate(model = "F5")) %>%
  filter(grepl("Treatment", term)) %>% 
  mutate(diet = lastThree(term)) %>% 
  mutate(sex = ifelse(grepl("Sexmale", term), "male", "female")) %>% 
  filter(grepl("female", sex))
  
data$Treatment <- factor(data$Treatment, levels=c("CD", "NSD", "LSD", "HSD"))
data$Sex <- factor(data$Sex, levels=c("male", "female"))

#Male Glycogen
#Run Models
Y.0M.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F0"))
Y.1M.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F1"))
Y.2M.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F2"))
Y.3M.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F3"))
Y.4M.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F4"))
Y.5M.Mod <- lm(Glycogen~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F5"))

#Create Dataframe of Results (See Y.results.df)
lastThree <- function(x) substr(x, nchar(x)-2, nchar(x))
Y.M.results.df <- rbind(tidy(Y.0M.Mod) %>% mutate(model = "F0"),
                 tidy(Y.1M.Mod) %>% mutate(model = "F1"),
                 tidy(Y.2M.Mod) %>% mutate(model = "F2"),
                 tidy(Y.3M.Mod) %>% mutate(model = "F3"),
                 tidy(Y.4M.Mod) %>% mutate(model = "F4"),
                 tidy(Y.5M.Mod) %>% mutate(model = "F5")) %>%
  filter(grepl("Treatment", term)) %>% 
  mutate(diet = lastThree(term)) %>% 
  mutate(sex = ifelse(grepl("Sexfemale", term), "female", "male")) %>% 
  filter(!grepl("female", sex))

Y.results.df <- rbind(Y.F.results.df, Y.M.results.df)
colnames(Y.results.df)[c(1,6,7)] <- c("variable", "generation", "treatment") 



#Female Trehalose
data$Treatment <- factor(data$Treatment, levels=c("CD", "NSD", "LSD", "HSD"))
data$Sex <- factor(data$Sex, levels=c("female", "male"))

#Run Models
T.0F.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F0"))
T.1F.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F1"))
T.2F.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F2"))
T.3F.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F3"))
T.4F.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F4"))
T.5F.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F5"))

#Create Dataframe of Results (See T.results.df)
lastThree <- function(x) substr(x, nchar(x)-2, nchar(x))
T.F.results.df <- rbind(tidy(T.0F.Mod) %>% mutate(model = "F0"),
                 tidy(T.1F.Mod) %>% mutate(model = "F1"),
                 tidy(T.2F.Mod) %>% mutate(model = "F2"),
                 tidy(T.3F.Mod) %>% mutate(model = "F3"),
                 tidy(T.4F.Mod) %>% mutate(model = "F4"),
                 tidy(T.5F.Mod) %>% mutate(model = "F5")) %>%
  filter(grepl("Treatment", term)) %>% 
  mutate(diet = lastThree(term)) %>% 
  mutate(sex = ifelse(grepl("Sexmale", term), "male", "female")) %>% 
  filter(grepl("female", sex))
  
data$Treatment <- factor(data$Treatment, levels=c("CD", "NSD", "LSD", "HSD"))
data$Sex <- factor(data$Sex, levels=c("male", "female"))

#Male Trehalose
#Run Models
T.0M.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F0"))
T.1M.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F1"))
T.2M.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F2"))
T.3M.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F3"))
T.4M.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F4"))
T.5M.Mod <- lm(Trehalose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F5"))

#Create Dataframe of Results (See T.results.df)
lastThree <- function(x) substr(x, nchar(x)-2, nchar(x))
T.M.results.df <- rbind(tidy(T.0M.Mod) %>% mutate(model = "F0"),
                 tidy(T.1M.Mod) %>% mutate(model = "F1"),
                 tidy(T.2M.Mod) %>% mutate(model = "F2"),
                 tidy(T.3M.Mod) %>% mutate(model = "F3"),
                 tidy(T.4M.Mod) %>% mutate(model = "F4"),
                 tidy(T.5M.Mod) %>% mutate(model = "F5")) %>%
  filter(grepl("Treatment", term)) %>% 
  mutate(diet = lastThree(term)) %>% 
  mutate(sex = ifelse(grepl("Sexfemale", term), "female", "male")) %>% 
  filter(!grepl("female", sex))

T.results.df <- rbind(T.F.results.df, T.M.results.df)
colnames(T.results.df)[c(1,6,7)] <- c("variable", "generation", "treatment") 



#Female Glucose
data$Treatment <- factor(data$Treatment, levels=c("CD", "NSD", "LSD", "HSD"))
data$Sex <- factor(data$Sex, levels=c("female", "male"))

#Run Models
G.0F.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F0"))
G.1F.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F1"))
G.2F.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F2"))
G.3F.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F3"))
G.4F.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F4"))
G.5F.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F5"))

#Create Dataframe of Results (See G.results.df)
lastThree <- function(x) substr(x, nchar(x)-2, nchar(x))
G.F.results.df <- rbind(tidy(G.0F.Mod) %>% mutate(model = "F0"),
                 tidy(G.1F.Mod) %>% mutate(model = "F1"),
                 tidy(G.2F.Mod) %>% mutate(model = "F2"),
                 tidy(G.3F.Mod) %>% mutate(model = "F3"),
                 tidy(G.4F.Mod) %>% mutate(model = "F4"),
                 tidy(G.5F.Mod) %>% mutate(model = "F5")) %>%
  filter(grepl("Treatment", term)) %>% 
  mutate(diet = lastThree(term)) %>% 
  mutate(sex = ifelse(grepl("Sexmale", term), "male", "female")) %>% 
  filter(grepl("female", sex))
  
data$Treatment <- factor(data$Treatment, levels=c("CD", "NSD", "LSD", "HSD"))
data$Sex <- factor(data$Sex, levels=c("male", "female"))

#Male Glucose
#Run Models
G.0M.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F0"))
G.1M.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F1"))
G.2M.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F2"))
G.3M.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F3"))
G.4M.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F4"))
G.5M.Mod <- lm(Glucose~Sugar.Weight + Sex*Treatment, data=subset(data, Generation=="F5"))

#Create Dataframe of Results (See G.results.df)
lastThree <- function(x) substr(x, nchar(x)-2, nchar(x))
G.M.results.df <- rbind(tidy(G.0M.Mod) %>% mutate(model = "F0"),
                 tidy(G.1M.Mod) %>% mutate(model = "F1"),
                 tidy(G.2M.Mod) %>% mutate(model = "F2"),
                 tidy(G.3M.Mod) %>% mutate(model = "F3"),
                 tidy(G.4M.Mod) %>% mutate(model = "F4"),
                 tidy(G.5M.Mod) %>% mutate(model = "F5")) %>%
  filter(grepl("Treatment", term)) %>% 
  mutate(diet = lastThree(term)) %>% 
  mutate(sex = ifelse(grepl("Sexfemale", term), "female", "male")) %>% 
  filter(!grepl("female", sex))

G.results.df <- rbind(G.F.results.df, G.M.results.df)
colnames(G.results.df)[c(1,6,7)] <- c("variable", "generation", "treatment") 


#Combine the 3 Metabolite data frames
G.results.df$metabolite <- rep("Glucose", length(G.results.df$generation))
T.results.df$metabolite <- rep("Trehalose", length(T.results.df$generation))
Y.results.df$metabolite <- rep("Glycogen", length(Y.results.df$generation))
All <- rbind(Y.results.df, T.results.df, G.results.df) %>%
  mutate(pAdj = p.adjust(p.value, method = "fdr"))
All <- as.data.frame(All)
AllSig <- symnum(All$pAdj, corr = FALSE, na = FALSE, cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " "))
AllSig <- cbind(All, AllSig)
AllSig <- AllSig[c("metabolite", "generation", "treatment", "sex", "pAdj", "AllSig", "variable", "estimate", "std.error", "statistic", "p.value")]


AllSig <- AllSig[with(AllSig, order(treatment)),]
AllSig <- AllSig[with(AllSig, order(sex)),]
AllSig <- AllSig[with(AllSig, order(metabolite)),]
write.csv(AllSig, file = "Supplementary Table. PILOT.f4NA Treatment vs. Control Contrast FDR corrected 180417.csv")
```

Plots:
```{r}
PlotData <- data
PlotData <- PlotData[with(PlotData, order(Generation)),]
PlotData <- PlotData[complete.cases(PlotData), ]
Sugar <- PlotData

#Normalize Values Across Generations ((Treatment/Wt)/(Control/Wt))
#SUGARS (Glucose, Trehalose, Glycogen)
Sugar.m <- melt(Sugar, 
    id.vars=c("Generation", "Treatment", "Sex", "Sugar.Weight"), 
    measure.vars=c("Glucose", "Trehalose", "Glycogen"))
colnames(Sugar.m)[5] <- "Metabolite"
SW <- data.frame(Generation=character(), Sex=character(), Treatment=character(), variable=character(), value=numeric())
  for(i in unique(Sugar.m$Generation))
    for(j in unique(Sugar.m$Sex))
      for(k in unique(Sugar.m$Treatment))
        for(l in unique(Sugar.m$Metabolite)){
        temp <- subset(Sugar.m, Generation == i & Sex == j & Treatment == k & Metabolite == l)
        temp$SugarWt <- ((subset(Sugar.m, Generation == i & Sex == j & Treatment == k & Metabolite == l)$value)/(subset(Sugar.m, Generation == i & Sex == j & Treatment == k & Metabolite == l)$Sugar.Weight))
        SW <- rbind(SW, temp)}
SW.Norm <- data.frame(Study=character(), Generation=character(), Sex=character(), Treatment=character(), variable=character(), value=numeric())
  for(i in unique(SW$Generation))
    for(j in unique(SW$Sex))
      for(k in unique(SW$Treatment))
        for(l in unique(SW$Metabolite)){
        temp <- subset(SW, Generation == i & Sex == j & Treatment == k & Metabolite == l)
        temp$PercentMetabWt <- (subset(SW, Generation == i & Sex == j & Treatment == k & Metabolite == l)$SugarWt)/mean(subset(SW, Generation == i & Sex == j & Treatment == "CD" & Metabolite == l)$SugarWt)
SW.Norm <-  rbind(SW.Norm, temp)
      }

Sugar <- SW.Norm[,c(1:3,5,8)]
Glucose <- Sugar %>% filter(grepl("Glucose", Metabolite))
colnames(Glucose)[5] <- "Glucose"

Trehalose <- Sugar %>% filter(grepl("Trehalose", Metabolite))
colnames(Trehalose)[5] <- "Trehalose"

Glycogen <- Sugar %>% filter(grepl("Glycogen", Metabolite))
colnames(Glycogen)[5] <- "Glycogen"


#Females
F.G.N.p <- ggplot(subset(Glucose, Sex=="female" & Treatment=="NSD")) + geom_boxplot(aes(x=Generation, y=Glucose), fill="#cccccc") + ggtitle("Glucose") + ylab(" ") + xlab(" ") + theme_bw()  + scale_y_continuous(limits=c(0, 2.5)) + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed") + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.55, label = "**", cex=12) + 
  annotate("text", 2, y = 2.2, label = "", cex=12) + 
  annotate("text", 3, y = 1.43, label = "", cex=12) + 
  annotate("text", 4, y = 1.72, label = "", cex=12) + 
  annotate("text", 5, y = 1.78, label = "**", cex=12) + 
  annotate("text", 6, y = 1.28, label = "*", cex=12) +
  annotate("text", 6, y = 0.08, label = "A", cex=16) 
F.G.N.p

F.G.L.p <- ggplot(subset(Glucose, Sex=="female" & Treatment=="LSD")) + geom_boxplot(aes(x=Generation, y=Glucose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 1.4, label = "", cex=12) + 
  annotate("text", 2, y = 1.92, label = "", cex=12) + 
  annotate("text", 3, y = 1.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.45, label = "", cex=12) + 
  annotate("text", 5, y = 1.52, label = "**", cex=12) + 
  annotate("text", 6, y = 1.8, label = "", cex=12)  +
  annotate("text", 6, y = 0.08, label = "B", cex=16) 
F.G.L.p

F.G.C.p <- ggplot(subset(Glucose, Sex=="female" & Treatment=="CD")) + geom_boxplot(aes(x=Generation, y=Glucose), fill="#cccccc") + ggtitle("Glucose CD Female") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 1.4, label = "", cex=12) + 
  annotate("text", 2, y = 1.92, label = "", cex=12) + 
  annotate("text", 3, y = 1.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.45, label = "", cex=12) + 
  annotate("text", 5, y = 1.82, label = "", cex=12) + 
  annotate("text", 6, y = 1.8, label = "", cex=12)  +
  annotate("text", 6, y = 0.08, label = "", cex=16) 
F.G.C.p

F.G.H.p <- ggplot(subset(Glucose, Sex=="female" & Treatment=="HSD")) + geom_boxplot(aes(x=Generation, y=Glucose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.55, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.375, label = "", cex=12) + 
  annotate("text", 5, y = 1.47, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12)  +
  annotate("text", 6, y = 0.08, label = "C", cex=16) 
F.G.H.p


F.T.N.p <- ggplot(subset(Trehalose, Sex=="female" & Treatment=="NSD")) + geom_boxplot(aes(x=Generation, y=Trehalose), fill="#cccccc") + ggtitle("Trehalose") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.45, label = "", cex=12) + 
  annotate("text", 2, y = 2.05, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 2.25, label = "*", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "D", cex=16) 
F.T.N.p

F.T.L.p <- ggplot(subset(Trehalose, Sex=="female" & Treatment=="LSD")) + geom_boxplot(aes(x=Generation, y=Trehalose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.55, label = "", cex=12) + 
  annotate("text", 2, y = 1.15, label = "*", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 2.5, label = "*", cex=12) + 
  annotate("text", 6, y = 0.08, label = "E", cex=16) 
F.T.L.p

F.T.C.p <- ggplot(subset(Trehalose, Sex=="female" & Treatment=="CD")) + geom_boxplot(aes(x=Generation, y=Trehalose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.55, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.7, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=16) 
F.T.C.p

F.T.H.p <- ggplot(subset(Trehalose, Sex=="female" & Treatment=="HSD")) + geom_boxplot(aes(x=Generation, y=Trehalose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 2.45, label = "**", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.6, label = "*", cex=12) + 
  annotate("text", 5, y = 1.6, label = "", cex=12) + 
  annotate("text", 6, y = 1.5, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "F", cex=16)  
F.T.H.p


F.Y.N.p <- ggplot(subset(Glycogen, Sex=="female" & Treatment=="NSD")) + geom_boxplot(aes(x=Generation, y=Glycogen), fill="#cccccc") + ggtitle("Glycogen") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.45, label = "**", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.65, label = "", cex=12) + 
  annotate("text", 5, y = 2.45, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "G", cex=16)  
F.Y.N.p

F.Y.L.p <- ggplot(subset(Glycogen, Sex=="female" & Treatment=="LSD")) + geom_boxplot(aes(x=Generation, y=Glycogen), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.95, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 1.05, label = "**", cex=12) + 
  annotate("text", 4, y = 1.65, label = "", cex=12) + 
  annotate("text", 5, y = 2, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "H", cex=16)  
F.Y.L.p

F.Y.C.p <- ggplot(subset(Glycogen, Sex=="female" & Treatment=="CD")) + geom_boxplot(aes(x=Generation, y=Glycogen), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.95, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 2.05, label = "", cex=12) + 
  annotate("text", 4, y = 1.65, label = "", cex=12) + 
  annotate("text", 5, y = 2, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "E", cex=16)  
F.Y.C.p


F.Y.H.p <- ggplot(subset(Glycogen, Sex=="female" & Treatment=="HSD")) + geom_boxplot(aes(x=Generation, y=Glycogen), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 2.18, label = "", cex=12) + 
  annotate("text", 2, y = 2.08, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.6, label = "", cex=12) + 
  annotate("text", 6, y = 1.5, label = "", cex=12)  +
  annotate("text", 6, y = 0.08, label = "I", cex=16)  
F.Y.H.p




#Males
M.G.N.p <- ggplot(subset(Glucose, Sex=="male" & Treatment=="NSD")) + geom_boxplot(aes(x=Generation, y=Glucose), fill="#cccccc") + ggtitle("Glucose") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.55, label = "**", cex=12) + 
  annotate("text", 2, y = 1.75, label = "*", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.45, label = "", cex=12) + 
  annotate("text", 6, y = 1.18, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "A", cex=16) 
M.G.N.p

M.G.L.p <- ggplot(subset(Glucose, Sex=="male" & Treatment=="LSD")) + geom_boxplot(aes(x=Generation, y=Glucose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.55, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 1.65, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.4, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "B", cex=16)  
M.G.L.p

M.G.H.p <- ggplot(subset(Glucose, Sex=="male" & Treatment=="HSD")) + geom_boxplot(aes(x=Generation, y=Glucose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.55, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 2.35, label = "*", cex=12) + 
  annotate("text", 5, y = 1.3, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "C", cex=16) 
M.G.H.p


M.T.N.p <- ggplot(subset(Trehalose, Sex=="male" & Treatment=="NSD")) + geom_boxplot(aes(x=Generation, y=Trehalose), fill="#cccccc") + ggtitle("Trehalose") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.35, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.6, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "D", cex=16) 
M.T.N.p

M.T.L.p <- ggplot(subset(Trehalose, Sex=="male" & Treatment=="LSD")) + geom_boxplot(aes(x=Generation, y=Trehalose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.75, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.6, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "E", cex=16) 
M.T.L.p

M.T.H.p <- ggplot(subset(Trehalose, Sex=="male" & Treatment=="HSD")) + geom_boxplot(aes(x=Generation, y=Trehalose), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 2.15, label = "", cex=12) + 
  annotate("text", 2, y = 2.25, label = "**", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.6, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "F", cex=16)  
M.T.H.p


M.Y.N.p <- ggplot(subset(Glycogen, Sex=="male" & Treatment=="NSD")) + geom_boxplot(aes(x=Generation, y=Glycogen), fill="#cccccc") + ggtitle("Glycogen") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.5, label = "**", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "**", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.6, label = "", cex=12) + 
  annotate("text", 6, y = 1.25, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "G", cex=16)  
M.Y.N.p

M.Y.L.p <- ggplot(subset(Glycogen, Sex=="male" & Treatment=="LSD")) + geom_boxplot(aes(x=Generation, y=Glycogen), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 0.55, label = "", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.3, label = "", cex=12) + 
  annotate("text", 6, y = 1.27, label = "", cex=12) +
  annotate("text", 6, y = 0.08, label = "H", cex=16) 
M.Y.L.p

M.Y.H.p <- ggplot(subset(Glycogen, Sex=="male" & Treatment=="HSD")) + geom_boxplot(aes(x=Generation, y=Glycogen), fill="#cccccc") + ggtitle("") + ylab(" ") + xlab(" ") + theme_bw() + geom_hline(aes(yintercept=1.0), color="black", linetype="dashed")  + scale_y_continuous(limits=c(0, 2.5)) + theme(legend.position="none", axis.text=element_text(size=25), axis.title.y = element_text(size = rel(2.5), angle = 90), plot.title = element_text(size = rel(3), hjust = 0.5)) + 
  annotate("text", 1, y = 2.35, label = "*", cex=12) + 
  annotate("text", 2, y = 1.75, label = "", cex=12) + 
  annotate("text", 3, y = 0.55, label = "", cex=12) + 
  annotate("text", 4, y = 1.75, label = "", cex=12) + 
  annotate("text", 5, y = 1.35, label = "", cex=12) + 
  annotate("text", 6, y = 0.08, label = "", cex=12)  +
  annotate("text", 6, y = 0.08, label = "I", cex=16) 
M.Y.H.p


f <- grid.arrange(F.G.N.p, F.T.N.p, F.Y.N.p, F.G.L.p, F.T.L.p, F.Y.L.p, F.G.H.p, F.T.H.p, F.Y.H.p, nrow=3, top=textGrob("Females", gp = gpar(fontface=2, fontsize=60)), bottom=textGrob("Generations", gp = gpar(fontface=1, fontsize=35)), left=textGrob("HSD                                               LSD                                                 NSD \n% relative to CD mean                % relative to CD mean                  % relative to CD mean", rot=90, gp = gpar(fontface=1, fontsize=35)))
# 
ggsave("Pilot All Females Ch2.png", f, width = 30, height = 20, units = "in")


m <- grid.arrange(M.G.N.p, M.T.N.p, M.Y.N.p, M.G.L.p, M.T.L.p, M.Y.L.p, M.G.H.p, M.T.H.p, M.Y.H.p, nrow=3, top=textGrob("Males", gp = gpar(fontface=2, fontsize=60)), bottom=textGrob("Generations", gp = gpar(fontface=1, fontsize=35)), left=textGrob("HSD                                          LSD                                        NSD \n% relative to CD mean          % relative to CD mean         % relative to CD mean", rot=90, gp = gpar(fontface=1, fontsize=35)))

ggsave("Pilot Supplementary Figure 2_Male All.png", m, width = 30, height = 20, units = "in")

```



